name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Submit dependency snapshot
      uses: advanced-security/maven-dependency-submission-action@v4
      with:
        package-url: 'pkg:maven/org.apache.logging.log4j/log4j-api@2.24.3?type=jar'
        distribution: 'release'  # 必須の入力を追加
