name: Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Maven
        run: mvn clean verify

      - name: Upload Jacoco coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco
